lenovo/python-redfish-lenovo

- README.md
XuLei： update readme for format and typo fix.
> Fix read typo and optimize the format.

- examples/update_firmware.py
Modify Targets parameter from Necessary to Optional.
Modify variables definition.
> Modify update firmware function for 19A

- examples/update_firmware.py
Modified update firmware function,  increase support for TFTP services.
> Update script update_firmware.py feature for support TFTP server.

- examples/clear_system_log.py
- examples/disable_bmc_user.py
- examples/enable_bmc_user.py
- examples/enable_secure_boot.py
- examples/get_bmc_inventory.py
- examples/get_bmc_ntp.py
- examples/get_cpu_inventory.py
- examples/get_fw_inventory.py
- examples/get_nic_inventory.py
- examples/get_psu_inventory.py
- examples/get_schema.py
- examples/get_serial_interfaces.py
- examples/get_system_inventory.py
- examples/get_system_log.py
- examples/get_system_reset_types.py
- examples/get_virtual_media.py
- examples/lenovo_utils.py
- examples/mount_virtual_media.py
- examples/reset_secure_boot.py
- examples/restart_bmc.py
- examples/set_bios_attribute.py
- examples/set_bmc_ntp.py
- examples/set_bmc_vlanid.py
- examples/set_networkprotocol.py
- examples/set_power_limit.py
- examples/set_serial_interfaces.py
- examples/set_server_asset_tag.py
- examples/set_server_boot_once.py
- examples/umount_virtual_media.py
- examples/update_bmc_user_password.py
Add below enhancement:
- follow ActionInfo parameter requirement to fill request body if ActionInfo is provided
- add property existing check before use it
- get etag to set If-Match precondition for some patch operation
- set _MAXHEADERS to avoid header over 100 error
- add 204 response code check besides 200 for patch operation
- enhance get_nic_inventory.py
- bug fix and typo fix
> Enhance scripts to support more

- examples/get_bmc_inventory.py
Get bmc EthernetInterfaces for bmc inventory getting
> Get bmc EthernetInterfaces for bmc inventory getting

- examples/lenovo_mount_virtual_media.py
- examples/lenovo_umount_virtual_media.py
Add lenovo OEM scripts to mount/umount virtual media to support both 18D and 19A version of XCC.
> Add new scripts lenovo_mount/umount_virtual_media.py

- examples/mount_virtual_media.py
- examples/umount_virtual_media.py
Add the comments about XCC version dependency and how to mount/umount on old XCC version
> Add the comments about XCC version dependency and how to mount/umount on old XCC version

- examples/get_schema.py
> support schema file download

- examples/config.ini
add comment for special char % in password
> add comment for special char % in password

- examples/lenovo_get_cpu_inventory.py
add Lenovo specific script to get cpu inventory including Lenovo CacheInfo
> add Lenovo specific script to get cpu inventory

- examples/get_memory_inventory.py
add member parameter for memory inventory get script
> add member parameter for memory inventory get script

- examples/get_bios_bootmode.py
- examples/set_bios_bootmode_legacy.py
- examples/set_bios_bootmode_uefi.py
fix issue-22 change boot mode not work
> fix issue-22 change boot mode not work

- examples/add_event_subscriptions.py
- examples/lenovo_create_bmc_user.py
- examples/lenovo_mount_virtual_media.py
- examples/lenovo_utils.py
- examples/mount_virtual_media.py
- examples/send_test_event.py
- examples/update_firmware.py
add examples for some scripts to help using them
> add examples for some scripts to help using them

- examples/restart_bmc.py
- examples/set_bmc_vlanid.py
- examples/set_networkprotocol.py
- examples/update_bmc_user_password.py
remove useless parameter system_id description
> remove useless parameter system_id description

- examples/lenovo_get_bmc_user_global.py
- examples/lenovo_set_bmc_user_global.py
add new script to set global setting for bmc user
> add new script to set global setting for bmc user

- examples/get_bios_bootmode.py
- examples/lenovo_set_serial_interfaces.py
- examples/reset_bios_default.py
- examples/set_chassis_indicator_led.py
- examples/set_serial_interfaces.py
Enhance scripts to support more2
> Enhance scripts to support more2

- examples/get_pci_inventory.py
- examples/lenovo_create_bmc_user.py
- examples/lenovo_delete_bmc_user.py
- examples/lenovo_get_bmc_user_accounts.py
> Add script get pci device

- examples/lenovo_create_bmc_user.py
- examples/lenovo_delete_bmc_user.py
- examples/lenovo_get_bmc_user_accounts.py
update bmc user manage scripts to support more
> update bmc user manage scripts to support more

- examples/get_power_limit.py
- examples/get_power_metrics.py
check whether target property exist before use them
> check whether target property exist before use them

- examples/lenovo_bmc_config_restore.py
- examples/lenovo_get_bmc_user_global.py
- examples/lenovo_mount_virtual_media.py
- examples/lenovo_set_bmc_user_global.py
- examples/lenovo_umount_virtual_media.py
- examples/mount_virtual_media.py
- examples/umount_virtual_media.py
- examples/update_bmc_user_password.py
enhance update_bmc_user_password.py to allow default account password changing;
enhance lenovo_bmc_config_restore.py to support updated oem schema definition;
add script description in lenovo_get_bmc_user_global.py and lenovo_set_bmc_user_global.py;
use basic auth instead of session in *mount_virtual_media.py and *umount_virtual_media.py
> Enhance scripts 20190919

- examples/get_chassis_indicator_led.py
- examples/get_fan_inventory.py
- examples/get_power_limit.py
- examples/get_power_metrics.py
- examples/get_power_redundancy.py
- examples/get_temperatures_inventory.py
- examples/get_volt_inventory.py
- examples/set_power_limit.py
only skip chassis without ComputerSystems in Links when multi-chassis exist
> enhance valid chassis check logic

- examples/get_chassis_indicator_led.py
- examples/get_fan_inventory.py
- examples/get_power_limit.py
- examples/get_power_metrics.py
- examples/get_power_redundancy.py
- examples/get_temperatures_inventory.py
- examples/get_volt_inventory.py
- examples/set_power_limit.py
- examples/set_serial_interfaces.py
enhance set serial interfaces script to support interfaceid that is not digit too
> Enhance set serial script

- examples/lenovo_create_bmc_user.py
- examples/lenovo_delete_bmc_user.py
support POST action for new user create, and support DELETE action for user delete
> enhance user create and delete scripts

- examples/send_test_event.py
support different parameter requirement for test event sending
> support different parameter requirement

- examples/add_event_subscriptions.py
- examples/send_test_event.py
support multi-versions EventService schema for subscription adding and test event sending
> support multi-versions EventService schema

- examples/get_metric_definiton_report.py
add new script get_metric_definiton_report.py
> add new script get_metric_definiton_report.py

- examples/manage_inventory.py
add new script manage_inventory.py which can get all inventories or pecified inventory
> add new script manage_inventory.py for getting all inventories

- examples/get_pci_inventory.py
- examples/set_bmc_ipv4.py
If no pcidevice in system, try to get pcidevice info from Chassis
> Enhance get pci script 20200213

- examples/get_bios_attribute_metadata.py
- examples/get_bmc_inventory.py
- examples/get_server_boot_once.py
- examples/set_bmc_timezone.py
- examples/set_power_state.py
- examples/set_server_boot_once.py
get BootSourceOverrideMode and BootSourceOverrideEnabled as well as BootSourceOverrideTarget, support mode specifying when setting bo
ot once
> Enhance get set bootonce scripts 20200304

- examples/reset_secure_boot.py
- examples/send_test_event.py
enhance script to fill in payload from ActionInfo's parameter definition if ActionInfo uri existing
> enhance script to fill in payload from ActionInfo's requirement

- examples/disable_bmc_user.py
- examples/enable_bmc_user.py
- examples/get_schema.py
- examples/lenovo_delete_bmc_user.py
> remove manually checking for required parameter

- examples/lenovo_ldap_certificate_add.py
/redfish/v1/AccountService/LDAP/Certificates
> enhance script to support standard LDAP certificate API 

- examples/lenovo_set_bmc_user_global.py
AccountLockoutDuration must not be 0 and must be a multiple of 60.
> Add checking for The input value for API property AccountLockoutDuration

- examples/lenovo_bmc_config_backup.py
- examples/lenovo_bmc_config_restore.py
check property httpport first before using and set default value if getting from config.ini failed
> check property httpport first before using

- examples/update_firmware.py
Support MultipartHttpPush to update
> Update firmware dev

- examples/lenovo_export_ffdc_data.py
support SR635/SR655 to download FFDC via SFTP for new firmware. And check firmware version to know SR635/SR655 download should use HTTP or SFTP
> support SR635/SR655 to download FFDC via SFTP for new firmware

- README.md
add requests package install guide and install note for configparser on python2.7
> add requests package install guide and install note for configparser

- examples/manage_inventory.py
update function names which have been changed to be consistent with file name
> update function names

- examples/get_psu_inventory.py
add properties HotPluggable/LastPowerOutputWatts/InputRanges/LineInputVoltageType/Location and Oem properties
> add properties

- examples/lenovo_mount_virtual_media.py
> add AMD 1P support for CIFS

- examples/lenovo_set_bmc_dns.py
> Set DNS for AMD 1P

- examples/lenovo_update_firmware.py
multiparthttppushURI_oem and json file bug fix
> Multiparthttppush bug fix

- examples/raw_command_get.py
- examples/raw_command_patch.py
- examples/raw_command_post.py
and add resource_uri example for raw_command_get script
> add logout handling when exception for raw_command_* scripts

- examples/lenovo_mount_virtual_media.py
- examples/mount_virtual_media.py
- examples/umount_virtual_media.py
mount_virtual_media support CIFS to mount for AMD1P && Variable name change
> support CIFS to mount for AMD1P && Variable name change

- examples/lenovo_mount_virtual_media.py
- examples/mount_virtual_media.py
if inserted is specified without value, set it to default value 1, to fix issue of 'The request could not be completed due to a conflict with the current state of the resource'
> Fix issue#9 Mount Virtual Media

- examples/get_chassis_inventory.py
add new feature: get chassis iventory
> add new feature: get chassis inventory

- examples/lenovo_ldap_certificate_add.py
For AMD1P,If the certificate already exists, upload it with the replace URL
> Modify lenovo_ldap_certificate_add. 

- products_supported.txt
Remove power capping(Set_power_limit)from Genoa
> Updated products supported

- products_supported.txt
lenovo_ekms_localcache_setting.py
set_raid_encryption_mode.py
lenovo_callhome_setting.py
lenovo_set_amt.py
firmware_startupdate.py
> Updated product scope by adding new support.

- products_supported.txt
Update product supported scope for EGS &Genoa
> Update product supported scope

- examples/lenovo_set_serial_interfaces.py
in lenovo_set_serial_interfaces
> Check whether the BHS has serial interfaces

- products_supported.txt
Update product support scope by adding SR630 V4.
> Update product support scope

- examples/lenovo_callhome_setting.py
Allow to set CallHome->Machine Location on XCC as shown here:
> Add CallHome machine location settings
